// Centralized site content. Add a new language by adding a key with the same shape.
export type Lang = 'en' | 'sv';

export const siteContent = {
  en: {
    nav: {
      tagline: '…Creating the Future',
      whoWeAre: 'Who We Are',
      whatWeDo: 'What We Do',
      contact: 'Contact',
      getInTouch: 'Get in touch',
      who: [
        { label: 'This is Nordamp Energy', href: '#backed' },
        { label: '#…Creating the Future', href: '#top' },
        { label: 'Our Values', href: '#', soon: true },
        { label: 'Our Strategy', href: '#', soon: true },
        { label: 'Management', href: '#', soon: true },
      ],
      what: [
        { label: 'Projects', href: '#', soon: true },
        { label: 'Paper & Pulp', href: '#', soon: true },
        { label: 'Renewable Energy Solutions', href: '#', soon: true },
        { label: 'Agriculture', href: '#', soon: true },
        { label: 'Maintenance', href: '#', soon: true },
        { label: 'Services', href: '#services' },
        { label: 'Electrification & Automation', href: '#services' },
        { label: 'Radiation', href: '#', soon: true },
        { label: 'Digital & AI', href: '#', soon: true },
      ],
    },
    hero: {
      eyebrow: "Owner's engineer · Commissioning · Electrical safety",
      titlePre: 'Independent engineering on the ',
      titleHighlight: "owner's",
      titlePost: ' side of the table.',
      lead: 'Nordamp Energy de-risks grid, nuclear and industrial projects across Finland, Sweden and Norway — from design review and commissioning to named electrical-safety responsibility.',
      ctaPrimary: 'Discuss a project',
      ctaSecondary: 'What we do',
      metaFI: 'FI · Nordamp Oy',
      metaSE: 'SE / NO · AKOSKI AB',
      boardHead: 'Sectors we commission',
      live: 'Live',
      placeholder: 'Placeholder',
      slides: [
        { key: 'grid', tag: 'GRID', title: 'Substation & transmission commissioning' },
        { key: 'nuclear', tag: 'NUCLEAR', title: 'SMR & reactor safety readiness' },
        { key: 'steel', tag: 'GREEN STEEL', title: 'Process electrification & handover' },
        { key: 'hydro', tag: 'HYDROPOWER', title: 'Refurbishment & controls' },
      ],
    },
    band: {
      caption: 'The build-out we help owners execute — safely and to standard',
      stats: [
        { num: '≈180', unit: 'bn SEK', desc: 'Swedish transmission grid, 2025–2035 (Svenska kraftnät)' },
        { num: '≤220', unit: 'bn SEK', desc: 'Swedish new nuclear — state loan frame, 12 years' },
        { num: '≈200', unit: 'bn NOK', desc: 'Norwegian grid over the next decade (Statnett)' },
        { num: '3', unit: 'markets', desc: 'Finland · Sweden · Norway — one methodology' },
      ],
    },
    services: {
      eyebrow: 'What we do',
      title: 'The full project lifecycle — advise, review, commission, assure.',
      intro:
        "An independent expertise layer that big rental houses and EPC contractors don't provide: we protect the owner's interest from first drawing to final handover.",
      items: [
        { idx: 'S/01', title: "Owner's engineer", desc: 'We sit on your side of the table — managing scope, design and vendors so the delivered plant matches what you paid for.' },
        { idx: 'S/02', title: 'Commissioning & handover', desc: 'Structured commissioning, punch and snag control, testing and handover documentation — so start-up is predictable, not a scramble.' },
        { idx: 'S/03', title: 'Electrical safety & named responsibility', desc: 'Named responsible-person duties as a service, plus safety cases and compliance to ESA, SS-EN 50110, FSE and SFS 6002.' },
        { idx: 'S/04', title: 'Design review & studies', desc: 'Independent review of electrical design and contracts — earthing, protection, sizing and constructability — before mistakes are built in.' },
        { idx: 'S/05', title: 'Alarm rationalisation (ISA-18.2)', desc: 'Audit and rationalise control-system alarms against ISA-18.2 to cut alarm floods and operator overload.' },
        { idx: 'S/06', title: 'Regulatory & compliance', desc: 'Documentation and liaison for Tukes, SSM and DSB — the approval-gating paperwork, handled properly.' },
      ],
    },
    approach: {
      eyebrow: 'How we engage',
      title: 'One line from study to safe start-up.',
      intro: 'A real sequence, not a menu. Each phase de-risks the next — and any phase can be a standalone engagement.',
      diagramNote: 'Radial · earthed neutral · no fault loop',
      steps: [
        { n: '01', title: 'Advise', desc: 'Owner-side studies, feasibility and requirement-setting before you commit to a vendor or a design.' },
        { n: '02', title: 'Review', desc: 'Independent design and contract review — electrical, safety and constructability — to catch risk on paper.' },
        { n: '03', title: 'Commission', desc: 'On-site commissioning management, testing and named electrical-safety responsibility through energisation.' },
        { n: '04', title: 'Assure', desc: 'Structured handover, as-built documentation and compliance sign-off — the plant proven, not just delivered.' },
      ],
    },
    markets: {
      eyebrow: 'Where we work',
      title: 'Three markets, three regulatory regimes, one team.',
      intro: 'Fluent across the Nordic electrical-safety codes — and able to translate between them for owners operating cross-border.',
      items: [
        { country: 'Finland', entity: 'Nordamp Oy', accent: false, focus: 'Home base and reference ground: transmission, industry, nuclear operations and hydrogen.', list: ['Fingrid grid & industrial electrification', 'CHP, biomass and fluidised-bed plants', 'Nuclear operations & modifications'], regime: 'Regime · Tukes / STUK · SFS 6002' },
        { country: 'Sweden', entity: 'AKOSKI AB', accent: true, focus: 'The largest pool of work: grid reinforcement, new nuclear and fossil-free industry.', list: ['Svenska kraftnät transmission programme', 'New nuclear — SMR & large-scale', 'Green steel & hydrogen (northern Sweden)'], regime: 'Regime · Elsäkerhetsverket / SSM · ESA' },
        { country: 'Norway', entity: 'via AKOSKI AB', accent: false, focus: 'Grid, hydropower renewal, offshore wind and the electrification of industry.', list: ['Statnett transmission investment', 'Hydropower refurbishment', 'Offshore wind & industry electrification'], regime: 'Regime · DSB / FSE · NEK' },
      ],
    },
    backed: {
      eyebrow: 'The track record we build on',
      title: 'Delivered through two established Nordic companies.',
      body: 'Nordamp Energy is the service brand. The work is contracted and invoiced through two operating entities — and stands on their combined engineering history across the Nordics, on both the supplier and the owner side of major energy projects.',
      entities: [
        { name: 'Nordamp Oy', reg: 'Finland · Reg. [FI-org.no.]', desc: 'Finnish operating entity — engineering, commissioning and digital services.', accent: false },
        { name: 'AKOSKI AB', reg: 'Sweden · Reg. [SE-org.no.]', desc: 'Swedish operating entity — serving the Swedish and Norwegian markets.', accent: true },
      ],
    },
    contact: {
      eyebrow: 'Start a conversation',
      title: "Let's de-risk your next project.",
      body: "Tell us the plant, the phase and the deadline. We'll tell you where the risk is — and how we'd take it off your plate.",
      button: 'Email the team',
      email: '[contact@nordampenergy.com]',
      phone: '[+358 / +46 phone]',
    },
    footer: {
      tagline: 'Independent owner\u2019s engineer and electrical-safety advisory for the Nordic energy build-out.',
      companyHeading: 'Company',
      links: [
        { label: 'Services', href: '#services' },
        { label: 'Approach', href: '#approach' },
        { label: 'Markets', href: '#markets' },
        { label: 'Backed by', href: '#backed' },
      ],
      entitiesHeading: 'Entities',
      entities: ['Nordamp Oy — Finland', 'AKOSKI AB — Sweden & Norway'],
      email: '[contact@nordampenergy.com]',
      copyright: '© 2026 Nordamp Energy',
      region: 'FI · SE · NO',
    },
  },

  sv: {
    nav: {
      tagline: '…Skapar framtiden',
      whoWeAre: 'Vilka vi är',
      whatWeDo: 'Vad vi gör',
      contact: 'Kontakt',
      getInTouch: 'Kontakta oss',
      who: [
        { label: 'Detta är Nordamp Energy', href: '#backed' },
        { label: '#…Skapar framtiden', href: '#top' },
        { label: 'Våra värderingar', href: '#', soon: true },
        { label: 'Vår strategi', href: '#', soon: true },
        { label: 'Ledning', href: '#', soon: true },
      ],
      what: [
        { label: 'Projekt', href: '#', soon: true },
        { label: 'Papper & Massa', href: '#', soon: true },
        { label: 'Förnybara energilösningar', href: '#', soon: true },
        { label: 'Jordbruk', href: '#', soon: true },
        { label: 'Underhåll', href: '#', soon: true },
        { label: 'Tjänster', href: '#services' },
        { label: 'Elektrifiering & Automation', href: '#services' },
        { label: 'Strålning', href: '#', soon: true },
        { label: 'Digitalt & AI', href: '#', soon: true },
      ],
    },
    hero: {
      eyebrow: 'Ägarens ingenjör · Driftsättning · Elsäkerhet',
      titlePre: 'Oberoende ingenjörskompetens på ',
      titleHighlight: 'ägarens',
      titlePost: ' sida av bordet.',
      lead: 'Nordamp Energy minskar riskerna i nät-, kärnkrafts- och industriprojekt i Finland, Sverige och Norge — från designgranskning och driftsättning till namngivet elsäkerhetsansvar.',
      ctaPrimary: 'Diskutera ett projekt',
      ctaSecondary: 'Vad vi gör',
      metaFI: 'FI · Nordamp Oy',
      metaSE: 'SE / NO · AKOSKI AB',
      boardHead: 'Sektorer vi driftsätter',
      live: 'Live',
      placeholder: 'Platshållare',
      slides: [
        { key: 'grid', tag: 'NÄT', title: 'Ställverk & transmissionsdriftsättning' },
        { key: 'nuclear', tag: 'KÄRNKRAFT', title: 'SMR & reaktorsäkerhet' },
        { key: 'steel', tag: 'GRÖNT STÅL', title: 'Processelektrifiering & överlämning' },
        { key: 'hydro', tag: 'VATTENKRAFT', title: 'Renovering & styrsystem' },
      ],
    },
    band: {
      caption: 'Utbyggnaden vi hjälper ägare att genomföra — säkert och enligt standard',
      stats: [
        { num: '≈180', unit: 'mdr SEK', desc: 'Svenska stamnätet, 2025–2035 (Svenska kraftnät)' },
        { num: '≤220', unit: 'mdr SEK', desc: 'Svensk ny kärnkraft — statlig låneram, 12 år' },
        { num: '≈200', unit: 'mdr NOK', desc: 'Norska nätet kommande decennium (Statnett)' },
        { num: '3', unit: 'marknader', desc: 'Finland · Sverige · Norge — en metodik' },
      ],
    },
    services: {
      eyebrow: 'Vad vi gör',
      title: 'Hela projektets livscykel — rådgivning, granskning, driftsättning, verifiering.',
      intro: 'Ett oberoende expertlager som stora uthyrningsbolag och EPC-entreprenörer inte erbjuder: vi skyddar ägarens intresse från första ritning till slutlig överlämning.',
      items: [
        { idx: 'S/01', title: 'Ägarens ingenjör', desc: 'Vi sitter på din sida av bordet — styr omfattning, design och leverantörer så att den levererade anläggningen motsvarar det du betalat för.' },
        { idx: 'S/02', title: 'Driftsättning & överlämning', desc: 'Strukturerad driftsättning, snag/punch-hantering, provning och överlämningsdokumentation — så att uppstart blir förutsägbar.' },
        { idx: 'S/03', title: 'Elsäkerhet & namngivet ansvar', desc: 'Namngivet ansvar som tjänst, plus säkerhetsfall och efterlevnad av ESA, SS-EN 50110, FSE och SFS 6002.' },
        { idx: 'S/04', title: 'Designgranskning & studier', desc: 'Oberoende granskning av elprojektering och kontrakt — jordning, skydd, dimensionering och byggbarhet — innan fel byggs in.' },
        { idx: 'S/05', title: 'Larmrationalisering (ISA-18.2)', desc: 'Granska och rationalisera styrsystemets larm mot ISA-18.2 för att minska larmflöden och operatörsöverbelastning.' },
        { idx: 'S/06', title: 'Regelverk & efterlevnad', desc: 'Dokumentation och kontakt med Tukes, SSM och DSB — den godkännandegrundande dokumentationen, korrekt hanterad.' },
      ],
    },
    approach: {
      eyebrow: 'Så arbetar vi',
      title: 'En linje från studie till säker uppstart.',
      intro: 'En verklig sekvens, inte en meny. Varje fas minskar risken i nästa — och varje fas kan vara ett fristående uppdrag.',
      diagramNote: 'Radiell · jordad neutral · ingen felslinga',
      steps: [
        { n: '01', title: 'Rådgivning', desc: 'Ägarsidans studier, förstudie och kravställning innan du binder dig till en leverantör eller design.' },
        { n: '02', title: 'Granskning', desc: 'Oberoende design- och kontraktsgranskning — el, säkerhet och byggbarhet — för att fånga risk på papperet.' },
        { n: '03', title: 'Driftsättning', desc: 'Driftsättningsledning på plats, provning och namngivet elsäkerhetsansvar genom spänningssättning.' },
        { n: '04', title: 'Verifiering', desc: 'Strukturerad överlämning, relationshandlingar och godkännande — anläggningen bevisad, inte bara levererad.' },
      ],
    },
    markets: {
      eyebrow: 'Var vi arbetar',
      title: 'Tre marknader, tre regelverk, ett team.',
      intro: 'Flytande i de nordiska elsäkerhetsregelverken — och kan översätta mellan dem för ägare med gränsöverskridande verksamhet.',
      items: [
        { country: 'Finland', entity: 'Nordamp Oy', accent: false, focus: 'Hemmabas och referensmark: transmission, industri, kärnkraftsdrift och vätgas.', list: ['Fingrid-nät & industriell elektrifiering', 'Kraftvärme, biomassa och fluidbäddspannor', 'Kärnkraftsdrift & modifieringar'], regime: 'Regelverk · Tukes / STUK · SFS 6002' },
        { country: 'Sverige', entity: 'AKOSKI AB', accent: true, focus: 'Den största mängden arbete: nätförstärkning, ny kärnkraft och fossilfri industri.', list: ['Svenska kraftnäts transmissionsprogram', 'Ny kärnkraft — SMR & storskaligt', 'Grönt stål & vätgas (norra Sverige)'], regime: 'Regelverk · Elsäkerhetsverket / SSM · ESA' },
        { country: 'Norge', entity: 'via AKOSKI AB', accent: false, focus: 'Nät, vattenkraftsförnyelse, havsbaserad vind och industrins elektrifiering.', list: ['Statnetts transmissionsinvestering', 'Renovering av vattenkraft', 'Havsvind & industrielektrifiering'], regime: 'Regelverk · DSB / FSE · NEK' },
      ],
    },
    backed: {
      eyebrow: 'Meritlistan vi bygger på',
      title: 'Levereras genom två etablerade nordiska bolag.',
      body: 'Nordamp Energy är servicevarumärket. Arbetet kontrakteras och faktureras via två operativa bolag — och vilar på deras samlade ingenjörshistorik i Norden, på både leverantörens och ägarens sida av stora energiprojekt.',
      entities: [
        { name: 'Nordamp Oy', reg: 'Finland · Org. [FI-org.nr]', desc: 'Finskt operativt bolag — ingenjörstjänster, driftsättning och digitala tjänster.', accent: false },
        { name: 'AKOSKI AB', reg: 'Sverige · Org. [SE-org.nr]', desc: 'Svenskt operativt bolag — betjänar den svenska och norska marknaden.', accent: true },
      ],
    },
    contact: {
      eyebrow: 'Inled ett samtal',
      title: 'Låt oss minska risken i ditt nästa projekt.',
      body: 'Berätta om anläggningen, fasen och deadline. Vi berättar var risken finns — och hur vi tar den från ditt bord.',
      button: 'Mejla teamet',
      email: '[contact@nordampenergy.com]',
      phone: '[+358 / +46 telefon]',
    },
    footer: {
      tagline: 'Oberoende ägaringenjör och elsäkerhetsrådgivning för den nordiska energiutbyggnaden.',
      companyHeading: 'Bolaget',
      links: [
        { label: 'Tjänster', href: '#services' },
        { label: 'Arbetssätt', href: '#approach' },
        { label: 'Marknader', href: '#markets' },
        { label: 'Bygger på', href: '#backed' },
      ],
      entitiesHeading: 'Bolag',
      entities: ['Nordamp Oy — Finland', 'AKOSKI AB — Sverige & Norge'],
      email: '[contact@nordampenergy.com]',
      copyright: '© 2026 Nordamp Energy',
      region: 'FI · SE · NO',
    },
  },
} as const;

export type Content = (typeof siteContent)['en'];
